// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  读取全部行；行序即界面顺序，前端不再排序。 */
	loadNotes: () => __TAURI_INVOKE<string[]>("load_notes"),
	/**  整文件重写（临时文件 + rename 原子替换）。 */
	saveNotes: (lines: string[]) => __TAURI_INVOKE<null>("save_notes", { lines }),
	/**  前端上报日志：经全局级别过滤，被过滤的日志不落盘（前端有本地缓存预判）。 */
	logMsg: (level: string, message: string) => __TAURI_INVOKE<void>("log_msg", { level, message }),
	/**  查询当前全局最低日志级别（小写字符串，供前端启动时同步缓存）。 */
	getLogLevel: () => __TAURI_INVOKE<string>("get_log_level"),
	/**  运行时热切全局最低日志级别，并 emit 事件让前端刷新缓存。 */
	setLogLevel: (level: string) => __TAURI_INVOKE<null>("set_log_level", { level }),
};

/** Events */
export const events = {
	logLevelChanged: makeEvent<LogLevelChanged>("log-level-changed"),
};

/* Types */
/**  日志级别变更事件（payload 为新级别小写字符串），前端监听后刷新本地缓存。 */
export type LogLevelChanged = string;

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

