// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  读取某块面板的全部行；行序即界面顺序，前端不再排序。 */
	loadNotes: (panel: Panel) => __TAURI_INVOKE<string[]>("load_notes", { panel }),
	/**  整文件重写某块面板（临时文件 + rename 原子替换）。另一块面板的文件不碰。 */
	saveNotes: (panel: Panel, lines: string[]) => __TAURI_INVOKE<null>("save_notes", { panel, lines }),
	/**
	 *  应用开机自启设置，并**回读实际状态**（前端据此判断要不要回滚开关）。
	 * 
	 *  不允许动注册表时**原样回显 `on`**（不读注册表）：那是「本环境不生效」，不是「设置失败」——
	 *  若回读真实值，dev 里开关会被自己打回去，e2e 的判据也会随机器状态飘。
	 */
	setAutostart: (on: boolean) => __TAURI_INVOKE<boolean>("set_autostart", { on }),
	/**  前端上报日志：经全局级别过滤，被过滤的日志不落盘（前端有本地缓存预判）。 */
	logMsg: (level: string, message: string) => __TAURI_INVOKE<void>("log_msg", { level, message }),
	/**  查询当前全局最低日志级别（小写字符串，供前端启动时同步缓存）。 */
	getLogLevel: () => __TAURI_INVOKE<string>("get_log_level"),
	/**  运行时热切全局最低日志级别，并 emit 事件让前端刷新缓存。 */
	setLogLevel: (level: string) => __TAURI_INVOKE<null>("set_log_level", { level }),
};

/** Events */
export const events = {
	logLevelChanged: makeEvent<LogLevelChanged>("log-level-changed"),
};

/* Types */
/**  日志级别变更事件（payload 为新级别小写字符串），前端监听后刷新本地缓存。 */
export type LogLevelChanged = string;

/**  哪块面板。序列化成 `"main"` / `"secondary"`（前端 `useNotes` 的 `Panel` 是同一个联合类型）。 */
export type Panel = "main" | "secondary";

/* Tauri Specta runtime */
type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

